name: Build

on:
  push:
    branches:
      - 1.20.4
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v4.0.0
      with:
        java-version: '21'
    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew build

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.2.0
      with:
       name: Artifact
       path: build/libs/
          
